name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'          

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Debug PNPM
        run: pnpm --version

      - name: Install Dependencies
        run: pnpm install

  test:
    name: Run Tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Debug PNPM
        run: pnpm --version
      
      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test      

  build:
    name: Build Project
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Debug PNPM
        run: pnpm --version
      
      - name: Install Dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: dist
  #         path: dist      

  # build-and-push-image:
  #   name: Build and Push Image
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USER }}
  #         password: ${{ secrets.DOCKERHUB_PW }}

  #     - name: Build Docker Image
  #       run: |
  #         docker build -t ${{ secrets.DOCKERHUB_USER }}/k8s-nodejs-cicd:latest .
  #         docker build -t ${{ secrets.DOCKERHUB_USER }}/k8s-nodejs-cicd:${{ github.sha }} .

  #     - name: Push Docker Image
  #       run: |
  #         docker push ${{ secrets.DOCKERHUB_USER }}/k8s-nodejs-cicd:latest
  #         docker push ${{ secrets.DOCKERHUB_USER }}/k8s-nodejs-cicd:${{ github.sha }}
